# Generated by Django 5.1.1 on 2024-11-20 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('short_description', models.TextField(max_length=512)),
                ('description_intro', models.TextField(max_length=512)),
                ('description_body', models.TextField(max_length=1024)),
                ('github_name', models.CharField(max_length=20, unique=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('other_url', models.URLField(null=True)),
                ('other_url_type', models.CharField(max_length=20, null=True)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('short_description', models.TextField(max_length=255)),
                ('description_intro', models.TextField(max_length=512)),
                ('description_body', models.TextField(max_length=1024)),
                ('youtube_url', models.URLField(null=True)),
                ('project_status', models.CharField(choices=[('O', 'Ongoing'), ('U', 'Upcoming'), ('C', 'Completed'), ('H', 'On Hold')], max_length=1)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(null=True)),
                ('contributors', models.ManyToManyField(to='api.developer')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('languages', models.ManyToManyField(to='api.language')),
                ('github_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url')),
            ],
        ),
    ]
