# Generated by Django 5.1.1 on 2024-11-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='description_body',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='description_intro',
        ),
        migrations.AddField(
            model_name='developer',
            name='description_experience',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='description_personal',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='featured_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
