# Generated by Django 5.1.1 on 2024-11-21 15:39

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_remove_developer_description_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='featured_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=api.models.get_dest_path),
        ),
    ]
