# Generated by Django 5.1.1 on 2024-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_developer_featured_project_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
