# Generated by Django 5.1.1 on 2024-11-22 14:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hover',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_year',
            field=models.IntegerField(null=True, validators=[api.models.project_date_validator]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.IntegerField(validators=[api.models.project_date_validator]),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.ManyToManyField(to='api.url'),
        ),
    ]
