# Generated by Django 5.1.4 on 2025-01-24 20:46

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_hover_alter_image_desc_alter_project_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='featured_project',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='short_description',
        ),
        migrations.AddField(
            model_name='developer',
            name='languages',
            field=models.ManyToManyField(to='api.language'),
        ),
        migrations.AddField(
            model_name='developer',
            name='picture_arms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_arms_picture', to='api.image'),
        ),
        migrations.AddField(
            model_name='developer',
            name='picture_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_personal_picture', to='api.image'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='other_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='other_url_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_picture', to='api.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='hover',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=api.models.get_dest_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[api.models.project_date_validator]),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
