name: Frontend Test and Lint
on: [push]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  run-jest-tests:
    if: ${{ startsWith(github.ref, 'refs/heads/frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'porogo/frontend/package-lock.json'
      - run: cd porogo/frontend
      - run: npm install
      - run: npm run test
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()    # run this step even if previous step failed
        with: 
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
          
  run-js-lint:
    if: ${{ startsWith(github.ref, 'refs/heads/frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.4
        with: 
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'porogo/frontend/package-lock.json'
      - run: cd porogo/frontend
      - run: npm install
      - run: npm run lint  
